title: EDM-Portfolio - Rizo Jose
description: "Enterprise Data Management Portfolio"
author: Rizo Jose

# Only use ONE theme (Minimal theme)
remote_theme: pages-themes/minimal@v0.2.0

logo: images/479699544_3975671589340061_694995400941422409_n.jpg

skills:
  - Time Management â°
  - Positive Attitude ğŸ˜Š
  - Good Listener ğŸ‘‚
  - Patience ğŸ•°ï¸
  - Adaptability ğŸ”„

show_downloads: false

github:
  is_project_page: true

plugins:
  - jekyll-remote-theme

include:
  - images
